<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';
$auth->check();

use CMS\Helpers;
use CMS\Post;

// ── Handle export download ────────────────────────────────────────────────────

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $auth->verifyCsrf($_POST['csrf_token'] ?? '');

    $siteTitle       = $db->getSetting('site_title', 'My CMS');
    $siteDescription = $db->getSetting('site_description', '');
    $siteUrl         = rtrim($db->getSetting('site_url', ''), '/');
    $authorName      = $db->getSetting('author_name', '');
    $username        = $config['admin']['username'] ?? 'admin';
    $exportDrafts    = isset($_POST['include_drafts']);

    // Load all posts (published + optionally drafts/scheduled).
    $statusFilter = $exportDrafts
        ? ["'published'", "'draft'", "'scheduled'"]
        : ["'published'"];
    $placeholders = implode(',', $statusFilter);
    $posts = $db->select(
        "SELECT * FROM posts WHERE status IN ({$placeholders}) ORDER BY published_at DESC, created_at DESC"
    );

    // Attach categories and tags to each post (batch in two queries).
    $postIds = array_column($posts, 'id');
    $catMap  = [];
    $tagMap  = [];

    if (!empty($postIds)) {
        $in  = implode(',', array_map('intval', $postIds));
        $catRows = $db->select(
            "SELECT pc.post_id, c.id, c.name, c.slug
               FROM post_categories pc
               JOIN categories c ON c.id = pc.category_id
              WHERE pc.post_id IN ({$in})"
        );
        foreach ($catRows as $row) {
            $catMap[(int) $row['post_id']][] = $row;
        }
        $tagRows = $db->select(
            "SELECT pt.post_id, t.id, t.name, t.slug
               FROM post_tags pt
               JOIN tags t ON t.id = pt.tag_id
              WHERE pt.post_id IN ({$in})"
        );
        foreach ($tagRows as $row) {
            $tagMap[(int) $row['post_id']][] = $row;
        }
    }

    // Load all categories and tags for the channel-level term elements.
    $allCategories = $db->select("SELECT * FROM categories ORDER BY name");
    $allTags       = $db->select("SELECT * FROM tags ORDER BY name");

    // ── Build XML ─────────────────────────────────────────────────────────────

    $now = date('D, d M Y H:i:s +0000');
    $filename = 'export-' . date('Y-m-d') . '.xml';

    header('Content-Type: text/xml; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-store');

    // Helper: wrap value in CDATA.
    $cdata = fn(string $v): string => '<![CDATA[' . $v . ']]>';

    // Helper: emit a wp: text element.
    $wpEl = function (string $tag, string $value) use ($cdata): string {
        return "\t\t<wp:{$tag}>{$cdata($value)}</wp:{$tag}>\n";
    };

    // Status map: clodd → WordPress.
    $statusMap = ['published' => 'publish', 'draft' => 'draft', 'scheduled' => 'future'];

    echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
    ?>
<!-- WordPress eXtended RSS (WXR) generated by Clodd CMS on <?= date('Y-m-d H:i:s') ?> -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
    <title><?= htmlspecialchars($siteTitle, ENT_XML1) ?></title>
    <link><?= htmlspecialchars($siteUrl, ENT_XML1) ?></link>
    <description><?= htmlspecialchars($siteDescription, ENT_XML1) ?></description>
    <pubDate><?= $now ?></pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url><?= htmlspecialchars($siteUrl, ENT_XML1) ?></wp:base_site_url>
    <wp:base_blog_url><?= htmlspecialchars($siteUrl, ENT_XML1) ?></wp:base_blog_url>

    <wp:author>
        <wp:author_id>1</wp:author_id>
        <wp:author_login><![CDATA[<?= htmlspecialchars($username) ?>]]></wp:author_login>
        <wp:author_email><![CDATA[]]></wp:author_email>
        <wp:author_display_name><![CDATA[<?= htmlspecialchars($authorName !== '' ? $authorName : $username) ?>]]></wp:author_display_name>
        <wp:author_first_name><![CDATA[]]></wp:author_first_name>
        <wp:author_last_name><![CDATA[]]></wp:author_last_name>
    </wp:author>

<?php foreach ($allCategories as $cat): ?>
    <wp:category>
        <wp:term_id><?= (int) $cat['id'] ?></wp:term_id>
        <wp:category_nicename><?= htmlspecialchars($cat['slug'], ENT_XML1) ?></wp:category_nicename>
        <wp:category_parent></wp:category_parent>
        <wp:cat_name><![CDATA[<?= htmlspecialchars($cat['name']) ?>]]></wp:cat_name>
<?php   if ($cat['description'] !== ''): ?>
        <wp:category_description><![CDATA[<?= htmlspecialchars($cat['description']) ?>]]></wp:category_description>
<?php   endif; ?>
    </wp:category>

<?php endforeach; ?>
<?php foreach ($allTags as $tag): ?>
    <wp:tag>
        <wp:term_id><?= 10000 + (int) $tag['id'] ?></wp:term_id>
        <wp:tag_slug><?= htmlspecialchars($tag['slug'], ENT_XML1) ?></wp:tag_slug>
        <wp:tag_name><![CDATA[<?= htmlspecialchars($tag['name']) ?>]]></wp:tag_name>
    </wp:tag>

<?php endforeach; ?>
<?php foreach ($posts as $post):
    $postId    = (int) $post['id'];
    $pubAt     = $post['published_at'] ?? $post['created_at'];
    $pubDate   = $pubAt ? date('D, d M Y H:i:s +0000', strtotime($pubAt)) : $now;
    $postDate  = $pubAt ? date('Y-m-d H:i:s', strtotime($pubAt)) : date('Y-m-d H:i:s');
    $status    = $statusMap[$post['status']] ?? 'draft';
    $permalink = $post['status'] === 'published' && $pubAt
        ? $siteUrl . '/posts/' . Post::datePath($pubAt, $post['slug']) . '/'
        : $siteUrl . '/?p=' . $postId;
    $html      = $builder->markdownToHtml($post['content']);
    $excerpt   = $post['excerpt'] ?? '';
    $postCats  = $catMap[$postId] ?? [];
    $postTags  = $tagMap[$postId] ?? [];
?>
    <item>
        <title><![CDATA[<?= htmlspecialchars($post['title']) ?>]]></title>
        <link><?= htmlspecialchars($permalink, ENT_XML1) ?></link>
        <pubDate><?= $pubDate ?></pubDate>
        <dc:creator><![CDATA[<?= htmlspecialchars($username) ?>]]></dc:creator>
        <guid isPermaLink="false"><?= htmlspecialchars($siteUrl . '/?p=' . $postId, ENT_XML1) ?></guid>
        <description></description>
        <content:encoded><![CDATA[<?= $html ?>]]></content:encoded>
        <excerpt:encoded><![CDATA[<?= htmlspecialchars($excerpt) ?>]]></excerpt:encoded>
        <wp:post_id><?= $postId ?></wp:post_id>
        <wp:post_date><![CDATA[<?= $postDate ?>]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[<?= $postDate ?>]]></wp:post_date_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[<?= htmlspecialchars($post['slug']) ?>]]></wp:post_name>
        <wp:status><![CDATA[<?= $status ?>]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[post]]></wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
<?php   foreach ($postCats as $cat): ?>
        <category domain="category" nicename="<?= htmlspecialchars($cat['slug'], ENT_XML1) ?>"><![CDATA[<?= htmlspecialchars($cat['name']) ?>]]></category>
<?php   endforeach; ?>
<?php   foreach ($postTags as $tag): ?>
        <category domain="post_tag" nicename="<?= htmlspecialchars($tag['slug'], ENT_XML1) ?>"><![CDATA[<?= htmlspecialchars($tag['name']) ?>]]></category>
<?php   endforeach; ?>
    </item>

<?php endforeach; ?>
</channel>
</rss>
<?php
    exit;
}

// ── Render admin page ─────────────────────────────────────────────────────────

$siteTitle  = $db->getSetting('site_title', 'My CMS');
$csrf       = $auth->csrfToken();
$flash      = $auth->getFlash();
$flashMsg   = $flash['message'] ?? '';
$flashType  = $flash['type']    ?? 'success';

$postCount  = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM posts WHERE status = 'published'")['n'] ?? 0);
$draftCount = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM posts WHERE status IN ('draft','scheduled')")['n'] ?? 0);
$catCount   = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM categories")['n'] ?? 0);
$tagCount   = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM tags")['n'] ?? 0);

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Export — <?= Helpers::e($siteTitle) ?></title>
    <link rel="stylesheet" href="/admin/assets/admin.css">
</head>
<body class="admin-page">

<?php require __DIR__ . '/partials/nav.php'; ?>

<main class="admin-main">
    <header class="page-header">
        <h1>Export</h1>
    </header>

    <?php if ($flashMsg !== ''): ?>
        <p class="alert alert--<?= Helpers::e($flashType) ?>"><?= Helpers::e($flashMsg) ?></p>
    <?php endif; ?>

    <div class="panel" style="max-width:520px">
        <h2>WordPress XML (WXR)</h2>
        <p>Download all posts in WordPress eXtended RSS format. You can import this file into any WordPress site using <strong>Tools → Import → WordPress</strong>.</p>

        <table class="data-table" style="margin-bottom:1.25rem">
            <tbody>
                <tr><td>Published posts</td><td style="text-align:right"><?= $postCount ?></td></tr>
                <tr><td>Drafts &amp; scheduled</td><td style="text-align:right"><?= $draftCount ?></td></tr>
                <tr><td>Categories</td><td style="text-align:right"><?= $catCount ?></td></tr>
                <tr><td>Tags</td><td style="text-align:right"><?= $tagCount ?></td></tr>
            </tbody>
        </table>

        <form method="post" action="/admin/export.php">
            <input type="hidden" name="csrf_token" value="<?= Helpers::e($csrf) ?>">
            <div style="margin-bottom:1rem">
                <label style="display:flex;align-items:center;gap:.5rem;cursor:pointer">
                    <input type="checkbox" name="include_drafts" value="1">
                    Include drafts and scheduled posts
                </label>
            </div>
            <button type="submit" class="btn">
                Download export file
            </button>
        </form>
    </div>

</main>

<script src="/admin/assets/admin.js"></script>
</body>
</html>
