<?php
// POST handler + GET-side data prep for the Export tab.
// Included from admin/tools.php after auth check. On POST, streams XML and exits.

use CMS\Post;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $auth->verifyCsrf($_POST['csrf_token'] ?? '');

    $siteTitle       = $db->getSetting('site_title', 'My CMS');
    $siteDescription = $db->getSetting('site_description', '');
    $siteUrl         = rtrim($db->getSetting('site_url', ''), '/');
    $authorName      = $db->getSetting('author_name', '');
    $timezone        = $db->getSetting('timezone', '');
    $username        = $config['admin']['username'] ?? 'admin';
    $exportDrafts    = isset($_POST['include_drafts']);

    // Load all posts (published + optionally drafts/scheduled).
    $statusFilter = $exportDrafts
        ? ["'published'", "'draft'", "'scheduled'"]
        : ["'published'"];
    $placeholders = implode(',', $statusFilter);
    $posts = $db->select(
        "SELECT * FROM posts WHERE status IN ({$placeholders}) ORDER BY published_at DESC, created_at DESC"
    );

    // Load pages (published + optionally drafts).
    $pageStatusFilter = $exportDrafts ? ["'published'", "'draft'"] : ["'published'"];
    $pagePlaceholders = implode(',', $pageStatusFilter);
    $pages = $db->select(
        "SELECT * FROM pages WHERE status IN ({$pagePlaceholders}) ORDER BY nav_order ASC, title ASC"
    );

    // Attach categories and tags to each post (batch in two queries).
    $postIds = array_column($posts, 'id');
    $catMap  = [];
    $tagMap  = [];

    if (!empty($postIds)) {
        $in  = implode(',', array_map('intval', $postIds));
        $catRows = $db->select(
            "SELECT pc.post_id, c.id, c.name, c.slug
               FROM post_categories pc
               JOIN categories c ON c.id = pc.category_id
              WHERE pc.post_id IN ({$in})"
        );
        foreach ($catRows as $row) {
            $catMap[(int) $row['post_id']][] = $row;
        }
        $tagRows = $db->select(
            "SELECT pt.post_id, t.id, t.name, t.slug
               FROM post_tags pt
               JOIN tags t ON t.id = pt.tag_id
              WHERE pt.post_id IN ({$in})"
        );
        foreach ($tagRows as $row) {
            $tagMap[(int) $row['post_id']][] = $row;
        }
    }

    // Load all categories and tags for the channel-level term elements.
    $allCategories = $db->select("SELECT * FROM categories ORDER BY name");
    $allTags       = $db->select("SELECT * FROM tags ORDER BY name");

    // ── Build XML ─────────────────────────────────────────────────────────────

    $now = date('D, d M Y H:i:s +0000');
    $filename = 'export-' . date('Y-m-d') . '.xml';

    header('Content-Type: text/xml; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-store');

    // Status map: clodd → WordPress.
    $statusMap = ['published' => 'publish', 'draft' => 'draft', 'scheduled' => 'future'];

    echo '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
    ?>
<!-- WordPress eXtended RSS (WXR) generated by Clodd CMS on <?= date('Y-m-d H:i:s') ?> -->
<rss version="2.0"
    xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:wfw="http://wellformedweb.org/CommentAPI/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:wp="http://wordpress.org/export/1.2/"
>
<channel>
    <title><?= htmlspecialchars($siteTitle, ENT_XML1) ?></title>
    <link><?= htmlspecialchars($siteUrl, ENT_XML1) ?></link>
    <description><?= htmlspecialchars($siteDescription, ENT_XML1) ?></description>
    <pubDate><?= $now ?></pubDate>
    <language>en-US</language>
    <wp:wxr_version>1.2</wp:wxr_version>
    <wp:base_site_url><?= htmlspecialchars($siteUrl, ENT_XML1) ?></wp:base_site_url>
    <wp:base_blog_url><?= htmlspecialchars($siteUrl, ENT_XML1) ?></wp:base_blog_url>

    <wp:author>
        <wp:author_id>1</wp:author_id>
        <wp:author_login><![CDATA[<?= htmlspecialchars($username) ?>]]></wp:author_login>
        <wp:author_email><![CDATA[]]></wp:author_email>
        <wp:author_display_name><![CDATA[<?= htmlspecialchars($authorName !== '' ? $authorName : $username) ?>]]></wp:author_display_name>
        <wp:author_first_name><![CDATA[]]></wp:author_first_name>
        <wp:author_last_name><![CDATA[]]></wp:author_last_name>
    </wp:author>

<?php foreach ($allCategories as $cat): ?>
    <wp:category>
        <wp:term_id><?= (int) $cat['id'] ?></wp:term_id>
        <wp:category_nicename><?= htmlspecialchars($cat['slug'], ENT_XML1) ?></wp:category_nicename>
        <wp:category_parent></wp:category_parent>
        <wp:cat_name><![CDATA[<?= htmlspecialchars($cat['name']) ?>]]></wp:cat_name>
<?php   if ($cat['description'] !== ''): ?>
        <wp:category_description><![CDATA[<?= htmlspecialchars($cat['description']) ?>]]></wp:category_description>
<?php   endif; ?>
    </wp:category>

<?php endforeach; ?>
<?php foreach ($allTags as $tag): ?>
    <wp:tag>
        <wp:term_id><?= 10000 + (int) $tag['id'] ?></wp:term_id>
        <wp:tag_slug><?= htmlspecialchars($tag['slug'], ENT_XML1) ?></wp:tag_slug>
        <wp:tag_name><![CDATA[<?= htmlspecialchars($tag['name']) ?>]]></wp:tag_name>
    </wp:tag>

<?php endforeach; ?>
<?php foreach ($posts as $post):
    $postId    = (int) $post['id'];
    $pubAt     = $post['published_at'] ?? $post['created_at'];
    $pubDate   = $pubAt ? date('D, d M Y H:i:s +0000', strtotime($pubAt)) : $now;
    $postDate  = $pubAt ? date('Y-m-d H:i:s', strtotime($pubAt)) : date('Y-m-d H:i:s');
    $status    = $statusMap[$post['status']] ?? 'draft';
    $permalink = $post['status'] === 'published' && $pubAt
        ? $siteUrl . '/posts/' . Post::datePath($pubAt, $post['slug'], $timezone) . '/'
        : $siteUrl . '/?p=' . $postId;
    $html      = $builder->markdownToHtml($post['content']);
    $excerpt   = $post['excerpt'] ?? '';
    $postCats  = $catMap[$postId] ?? [];
    $postTags  = $tagMap[$postId] ?? [];
?>
    <item>
        <title><![CDATA[<?= htmlspecialchars($post['title']) ?>]]></title>
        <link><?= htmlspecialchars($permalink, ENT_XML1) ?></link>
        <pubDate><?= $pubDate ?></pubDate>
        <dc:creator><![CDATA[<?= htmlspecialchars($username) ?>]]></dc:creator>
        <guid isPermaLink="false"><?= htmlspecialchars($siteUrl . '/?p=' . $postId, ENT_XML1) ?></guid>
        <description></description>
        <content:encoded><![CDATA[<?= $html ?>]]></content:encoded>
        <excerpt:encoded><![CDATA[<?= htmlspecialchars($excerpt) ?>]]></excerpt:encoded>
        <wp:post_id><?= $postId ?></wp:post_id>
        <wp:post_date><![CDATA[<?= $postDate ?>]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[<?= $postDate ?>]]></wp:post_date_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[<?= htmlspecialchars($post['slug']) ?>]]></wp:post_name>
        <wp:status><![CDATA[<?= $status ?>]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order>0</wp:menu_order>
        <wp:post_type><![CDATA[post]]></wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
<?php   foreach ($postCats as $cat): ?>
        <category domain="category" nicename="<?= htmlspecialchars($cat['slug'], ENT_XML1) ?>"><![CDATA[<?= htmlspecialchars($cat['name']) ?>]]></category>
<?php   endforeach; ?>
<?php   foreach ($postTags as $tag): ?>
        <category domain="post_tag" nicename="<?= htmlspecialchars($tag['slug'], ENT_XML1) ?>"><![CDATA[<?= htmlspecialchars($tag['name']) ?>]]></category>
<?php   endforeach; ?>
    </item>

<?php endforeach; ?>
<?php foreach ($pages as $page):
    $pageWpId  = 50000 + (int) $page['id'];
    $createdAt = $page['created_at'] ?? date('Y-m-d H:i:s');
    $pubDate   = date('D, d M Y H:i:s +0000', strtotime($createdAt));
    $postDate  = date('Y-m-d H:i:s', strtotime($createdAt));
    $status    = $page['status'] === 'published' ? 'publish' : 'draft';
    $permalink = $page['status'] === 'published'
        ? $siteUrl . '/' . $page['slug'] . '/'
        : $siteUrl . '/?page_id=' . $pageWpId;
    $html      = $builder->markdownToHtml($page['content']);
?>
    <item>
        <title><![CDATA[<?= htmlspecialchars($page['title']) ?>]]></title>
        <link><?= htmlspecialchars($permalink, ENT_XML1) ?></link>
        <pubDate><?= $pubDate ?></pubDate>
        <dc:creator><![CDATA[<?= htmlspecialchars($username) ?>]]></dc:creator>
        <guid isPermaLink="false"><?= htmlspecialchars($siteUrl . '/?page_id=' . $pageWpId, ENT_XML1) ?></guid>
        <description></description>
        <content:encoded><![CDATA[<?= $html ?>]]></content:encoded>
        <excerpt:encoded><![CDATA[]]></excerpt:encoded>
        <wp:post_id><?= $pageWpId ?></wp:post_id>
        <wp:post_date><![CDATA[<?= $postDate ?>]]></wp:post_date>
        <wp:post_date_gmt><![CDATA[<?= $postDate ?>]]></wp:post_date_gmt>
        <wp:comment_status><![CDATA[closed]]></wp:comment_status>
        <wp:ping_status><![CDATA[closed]]></wp:ping_status>
        <wp:post_name><![CDATA[<?= htmlspecialchars($page['slug']) ?>]]></wp:post_name>
        <wp:status><![CDATA[<?= $status ?>]]></wp:status>
        <wp:post_parent>0</wp:post_parent>
        <wp:menu_order><?= (int) $page['nav_order'] ?></wp:menu_order>
        <wp:post_type><![CDATA[page]]></wp:post_type>
        <wp:post_password></wp:post_password>
        <wp:is_sticky>0</wp:is_sticky>
    </item>

<?php endforeach; ?>
</channel>
</rss>
<?php
    exit;
}

// ── GET-side data prep ─────────────────────────────────────────────────────

$csrf       = $auth->csrfToken();

$postCount  = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM posts WHERE status = 'published'")['n'] ?? 0);
$draftCount = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM posts WHERE status IN ('draft','scheduled')")['n'] ?? 0);
$exportPageCount  = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM pages WHERE status = 'published'")['n'] ?? 0);
$pageDraftCount   = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM pages WHERE status = 'draft'")['n'] ?? 0);
$catCount   = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM categories")['n'] ?? 0);
$tagCount   = (int) ($db->selectOne("SELECT COUNT(*) AS n FROM tags")['n'] ?? 0);
